services:
  misssolitude.api:
    build:
      context: .
      dockerfile: MissSolitude.API/Dockerfile
    container_name: misssolitude.api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgresDatabase;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgresDatabase:
        condition: service_healthy

  postgresDatabase:
    image: postgres:16
    container_name: postgresDatabase
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  misssolitude.ui:
    build:
      context: .
      dockerfile: MissSolitude.UI/Dockerfile
    container_name: misssolitude.ui
    ports:
      - "8081:80"
    depends_on:
      - misssolitude.api

volumes:
  postgresData:
